Update compile
oeps go back

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,222 +1,101 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env_dir>
 
-# bin/compile <build-dir> <cache-dir> <env-dir>
+# fail fast
+set -e
 
-install_ext () {
-    local ext=$1
-    local reason=${2:-}
-    local ext_ini="$BP_DIR/conf/php/conf.d/ext-$ext.ini"
-    local ext_dir=$(basename $(php-config --extension-dir))
-    if [[ -f "$ext_ini" ]]; then
-        if [[ ! -f "$PHP_EXT_DIR/$ext.so" ]]; then
-            curl --silent --location "${S3_URL}/extensions/${ext_dir}/${ext}.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
-            echo "- ${ext} (${reason}; downloaded, using 'ext-${ext}.ini')" | indent
-        else
-            echo "- ${ext} (${reason}; bundled, using 'ext-${ext}.ini')" | indent
-        fi
-        cp "${ext_ini}" "${BUILD_DIR}/.heroku/php/etc/php/conf.d"
-    elif [[ -f "${PHP_EXT_DIR}/${ext}.so" ]]; then
-        echo "extension = ${ext}.so" > "${BUILD_DIR}/.heroku/php/etc/php/conf.d/ext-${ext}.ini"
-        echo "- ${ext} (${reason}; bundled)" | indent
-    elif echo -n ${ext} | php -r 'exit((int)!extension_loaded(file_get_contents("php://stdin")));'; then
-        echo "- ${ext} (${reason}; enabled by default)" | indent
-    else
-        warning_inline "Unknown extension ${ext} (${reason}), install may fail!"
-    fi
-}
+#retrieve new relic env variables
+env_dir=$3
+if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+        export "$e=$(cat $env_dir/$e)"
+        :
+    done
+fi
 
-# fail hard
-set -o pipefail
-# fail harder
-set -eu
-# move hidden files too, just in case
+# config
+APACHE_VERSION="2.4.9"
+APACHE_PATH="apache"
+PHP_VERSION="5.5.10"
+PHP_PATH="php"
+PCRE_VERSION="8.34"
+
+BIN_DIR=$(dirname $0)
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+# include .files when moving things around
 shopt -s dotglob
 
-STACK=${STACK:-cedar} # Anvil has none
-BUILD_DIR=$1
-CACHE_DIR=$2/php
-mkdir -p "$CACHE_DIR"
-ENV_DIR=${3:-} # Anvil has none
-BP_DIR=$(cd $(dirname $0); cd ..; pwd)
-
-# convenience functions
-source $BP_DIR/bin/common.sh
-
-export_env_dir "$ENV_DIR" '^[A-Z_][A-Z0-9_]*$' '^(HOME|PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LD_LIBRARY_PATH|STACK)$'
-
-BUILDPACK_URL=${BUILDPACK_URL:-} # Anvil has none
-BUILDPACK_BRANCH=$(expr "$BUILDPACK_URL" : '^.*/heroku-buildpack-php#\(..*\)$' || expr "$BUILDPACK_URL" : '^.*/heroku-buildpack-php\.git#\(..*\)$' || true)
-BUILDPACK_BRANCH=${BUILDPACK_BRANCH:-master}
-BUILDPACK_OWNER=$(expr "$BUILDPACK_URL" : '^.*/\(..*\)/heroku-buildpack-php' || true)
-
-S3_URL="master"
-if [[ "$BUILDPACK_BRANCH" != v* && "$BUILDPACK_BRANCH" != "master" ]]; then
-    S3_URL="develop"
-fi
-S3_URL="https://lang-php.s3.amazonaws.com/dist-${STACK}-${S3_URL}"
-
 cd $BUILD_DIR
 
-if [[ -s "composer.json" ]]; then
-    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
-else
-    if [[ ! -f "composer.json" ]]; then
-        warning 'No composer.json found.
-Using index.php to declare PHP applications is considered legacy
-functionality and may lead to unexpected behavior.'
-    else
-        notice 'Your composer.json is completely empty.
-Please change its contents to at least "{}" so it is valid JSON.'
-    fi
-    echo "{}" > composer.json
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
 fi
 
-mkdir -p .heroku/php
+PCRE_URL="https://s3.amazonaws.com/mediaBunker/pcre-8.34.tar.gz"
+echo "-----> Bundling pcre version $PCRE_VERSION for apache"
+curl --silent --max-time 60 --location "$PCRE_URL" | tar xz
 
-export COMPOSER_HOME=$CACHE_DIR/.composer
-mkdir -p $COMPOSER_HOME
+APACHE_URL="https://s3.amazonaws.com/mediaBunker/apache-2.4.9.tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
 
-PHP_VERSION=
-HHVM_VERSION=
-runtimes=$(cd $BP_DIR/support/build; ls {php,hhvm}-*)
-if [[ $STACK == "cedar-14" ]]; then
-    # FIXME: remove once HHVM works on cedar-14
-    runtimes=$(cd $BP_DIR/support/build; ls php-*)
-fi
-engine="php"
+PHP_URL="https://s3.amazonaws.com/mediaBunker/php-5.5.10.tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
 
-PHP_VERSION="5.5.15"
-status "Installing system packages..."
-
-# we need to run things in here, set it up!
-ln -s $BUILD_DIR/.heroku /app/.heroku
-export PATH=/app/.heroku/php/bin:$PATH
-
-if [[ "${PHP_VERSION}" ]]; then
-    PHP_DIST_URL="$S3_URL/php-$PHP_VERSION.tar.gz"
-    echo "- PHP $PHP_VERSION" | indent
-    curl --silent --location "$PHP_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/php
-    PHP_EXT_DIR=$(php-config --extension-dir)
-    # update config files
-    mkdir -p $BUILD_DIR/.heroku/php/etc/php
-    cp $BP_DIR/conf/php/php.ini $BUILD_DIR/.heroku/php/etc/php
-    cp $BP_DIR/conf/php/php-fpm.conf $BUILD_DIR/.heroku/php/etc/php
-    mkdir -p $BUILD_DIR/.heroku/php/etc/php/conf.d
-    # remember the version for future upgrade handling
-    echo $PHP_VERSION > $CACHE_DIR/php_version
-fi
-if [[ "${HHVM_VERSION}" ]]; then
-    HHVM_DIST_URL="$S3_URL/hhvm-$HHVM_VERSION.tar.gz"
-    echo "- HHVM $HHVM_VERSION" | indent
-    curl --silent --location "$HHVM_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/php
-    echo $HHVM_VERSION > $CACHE_DIR/hhvm_version
-    # make HHVM accessible
-    export PATH=$PATH:/app/.heroku/php/usr/bin
-    # so it'll start. remember to use the full path to the binary, or we'll get an infinite loop
-    hhvm() { LD_LIBRARY_PATH=/app/.heroku/php/usr/lib/hhvm:/app/.heroku/php/usr/lib `which hhvm` "$@"; }
-    export -f hhvm
-fi
-
-APACHE_VERSION="2.4.10"
-APACHE_DIST_URL="$S3_URL/apache-$APACHE_VERSION.tar.gz"
-echo "- Apache $APACHE_VERSION" | indent
-curl --silent --location "$APACHE_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/php
-# Apache; copy in our config
-cp $BP_DIR/conf/apache2/httpd.conf.default $BUILD_DIR/.heroku/php/etc/apache2/httpd.conf
-# remember the version for future upgrade handling
-echo $APACHE_VERSION > $CACHE_DIR/apache2_version
-
-NGINX_VERSION="1.6.0"
-NGINX_DIST_URL="$S3_URL/nginx-$NGINX_VERSION.tar.gz"
-echo "- Nginx $NGINX_VERSION" | indent
-curl --silent --location "$NGINX_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/php
-# nginx; copy in our config
-cp $BP_DIR/conf/nginx/nginx.conf.default $BUILD_DIR/.heroku/php/etc/nginx/nginx.conf
-# remember the version for future upgrade handling
-echo $NGINX_VERSION > $CACHE_DIR/nginx_version
-
-# handle extensions for PHP
-if [[ "${PHP_VERSION}" ]]; then
-    status "Installing PHP extensions..."
-    install_ext "opcache" "automatic" 
-    install_ext "redis" "automatic" 
+if [ -n "$NEW_RELIC_LICENSE_KEY" ]; then
+    NEW_RELIC_URL="https://s3.amazonaws.com/mediaBunker/newrelic-4.7.5.43.tar.gz"
+    echo "-----> Found new relic license key, installing newrelic."
+    curl --silent --max-time 60 --location "$NEW_RELIC_URL" | tar xz
     
-fi
-
-status "Installing dependencies..."
-
-# check if we should use a composer.phar version bundled with the project
-if [[ -f "composer.phar" ]]; then
-    composer() {
-        $engine composer.phar "$@"
-    }
-    export -f composer
-    notice_inline "Found a composer.phar in root directory, will use it for install."
+    echo "-----> Setting new relic license key and app name ($NEW_RELIC_APP_NAME)"
+    sed -i "s|REPLACE_WITH_REAL_KEY|${NEW_RELIC_LICENSE_KEY}|g" $LP_DIR/conf/php.ini
+    sed -i "s|REPLACE_WITH_REAL_APP_NAME|${NEW_RELIC_APP_NAME}|g" $LP_DIR/conf/php.ini
+    
+    mkdir newrelic/logs/
+    touch newrelic/logs/agent.log
+    touch newrelic/logs/daemon.log
 else
-    curl --silent --location "$S3_URL/composer.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
-    composer() {
-        $engine `which composer` "$@"
-    }
-    export -f composer
-    composer self-update --no-interaction --quiet # TODO: specify a version once composer has stable releases
+    echo "-----> No new relic license key found. Set NEW_RELIC_LICENSE_KEY to use new relic!"
 fi
-# echo composer version for info purposes
-# tail to get rid of outdated version warnings (Composer sends those to STDOUT instead of STDERR)
-composer --version 2> /dev/null | tail -n 1 | indent
 
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
 
-# handle custom oauth keys
-COMPOSER_GITHUB_OAUTH_TOKEN=${COMPOSER_GITHUB_OAUTH_TOKEN:-}
-if [[ -n "$COMPOSER_GITHUB_OAUTH_TOKEN" ]]; then
-    if curl --fail --silent -H "Authorization: token $COMPOSER_GITHUB_OAUTH_TOKEN" https://api.github.com/rate_limit > /dev/null; then
-        composer config -g github-oauth.github.com "$COMPOSER_GITHUB_OAUTH_TOKEN" &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
-        notice_inline 'Using custom GitHub OAuth token in $COMPOSER_GITHUB_OAUTH_TOKEN'
-    else
-        error 'Invalid GitHub OAuth token in $COMPOSER_GITHUB_OAUTH_TOKEN'
-    fi
-else
-    # don't forget to remove any stored key if it's gone from the env
-    composer config -g --unset github-oauth.github.com &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
-    if curl --silent https://api.github.com/rate_limit | python -c 'import sys, json; sys.exit((json.load(sys.stdin)["resources"]["core"]["remaining"] > 0))'; then # yes, check > 0, not < 1 - exit status of 0 will trigger the if
-        notice "You've reached the GitHub API's request rate limit.
-Composer will now try and fall back to slower downloads from source.
-It's strongly recommended you use a custom OAuth token; for details, see
-http://devcenter.heroku.com/articles/php-support#custom-github-oauth-tokens"
-    fi
-fi
-# no need for the token to stay around in the env
-unset COMPOSER_GITHUB_OAUTH_TOKEN
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
 
-# install dependencies
-#composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction | indent
+cat >>boot.sh <<EOF
+#!/usr/bin/env bash
 
-composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires package 'heroku/heroku-buildpack-php'.
-This package may only be used as a dev dependency (in 'require-dev')!"
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
+done
 
-status "Preparing runtime environment..."
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+tail -F /app/newrelic/logs/agent.log &
+tail -F /app/newrelic/logs/daemon.log &
+export LD_LIBRARY_PATH=/app/php/ext
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
 
-# install this buildpack like a composer package
-# it will contain the apache/nginx/php configs and the boot script
-# TODO: warn if require-dev has the package using a different branch
-shopt -u dotglob # we don't want .git, .gitignore et al
-composer_vendordir=$(composer config vendor-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
-composer_bindir=$(composer config bin-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
-# figure out the package dir name to write to and copy to it
-hbpdir="$composer_vendordir/$(cat $BP_DIR/composer.json | python -c 'import sys, json; print json.load(sys.stdin)["name"]')"
-mkdir -p "$BUILD_DIR/$hbpdir"
-cp -r "$BP_DIR"/* "$BUILD_DIR/$hbpdir/"
-# make bin dir, just in case
-mkdir -p "$BUILD_DIR/$composer_bindir"
-# figure out shortest relative path from vendor/heroku/heroku-buildpack-php to vendor/bin (or whatever the bin dir is)
-relbin=$(python -c "import os.path; print os.path.relpath('$hbpdir', '$composer_bindir')")
-# collect bin names from composer.json
-#relbins=$(cat $BP_DIR/composer.json | python -c 'from __future__ import print_function; import sys, json; { print(sys.argv[1]+"/"+bin) for bin in json.load(sys.stdin)["bin"] }' $relbin)
-# link to bins
-cd $BUILD_DIR/$composer_bindir
-# ln -s $relbins .
-cd $BUILD_DIR
+chmod +x boot.sh
 
-# Update the PATH
-echo export PATH="/app/.heroku/php/bin:/app/.heroku/php/sbin:$PATH" | sudo tee -a /etc/environment
-export PATH="/app/.heroku/php/bin:/app/.heroku/php/sbin:$PATH"
-
+# clean the cache
+rm -rf $CACHE_DIR
